export const ROUTES = {
  ROOT: 'Root',
  AUTH: 'Auth',
  MAIN: 'Main',
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  ONBOARDING_WELCOME: 'OnboardingWelcome',
  ONBOARDING_NEXT: 'OnboardingNext',
  SIGN_IN: 'SignIn',
  FORGOT_ID: 'ForgotId',
  FORGOT_PASSWORD: 'ForgotPassword',
  SIGN_UP_TERMS: 'SignUpTerms',
  SIGN_UP_ID: 'SignUpId',
  SIGN_UP_PASSWORD: 'SignUpPassword',
  SIGN_UP_EMAIL: 'SignUpEmail',
  SIGN_UP_EMAIL_CODE: 'SignUpEmailCode',
  SIGN_UP_COUNTRY: 'SignUpCountry',
  SIGN_UP_BIRTH: 'SignUpBirth',
  SIGN_UP_FAVORITES: 'SignUpFavorites',
  SIGN_UP_DONE: 'SignUpDone',
  HOME_INTRO: 'HomeIntro',
  HOME_DISCOVER: 'HomeDiscover',
  LOUNGE: 'LoungeList',
  CLAN: 'ClanList',
  EVENTS: 'EventsHome',
  MY_PAGE: 'MyPage',
  POLL_DETAIL: 'PollDetail',
  RAFFLE_DETAIL: 'RaffleDetail',
  CLAN_DETAIL: 'ClanDetail',
  CLAN_POST_LIST: 'ClanPostList',
  CLAN_POST_DETAIL: 'ClanPostDetail',
  CLAN_POST_CREATE: 'ClanPostCreate',
};

export const TABS = {
  HOME: 'HomeTab',
  LOUNGE: 'LoungeTab',
  CLAN: 'ClanTab',
  EVENTS: 'EventsTab',
  MY: 'MyTab',
};
